#!/usr/bin/env npx tsx
/**
 * Pre-generates theme CSS at build time.
 *
 * The theme files (zocdoc.ts, schweiger.ts, etc.) call generateThemeSync() which
 * pulls in the entire @charm-ux/theming generator library (~170KB). By pre-generating
 * the CSS strings here and writing them to static files, the runtime bundle only
 * includes the CSS strings, not the generator.
 *
 * Run: pnpm -C packages/primitives generate-themes
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateThemeSync } from '@charm-ux/theming/generator';
import { zocdocTokenDefinition } from '../src/theme/zocdoc-tokens.js';
import { schweigerTokenDefinition } from '../src/theme/schweiger-tokens.js';
import { priviaTokenDefinition } from '../src/theme/privia-tokens.js';
import { womensCareTokenDefinition } from '../src/theme/womensCare-tokens.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, '../src/theme/generated');

interface ThemeConfig {
  name: string;
  definition: Parameters<typeof generateThemeSync>[0];
}

const themes: ThemeConfig[] = [
  { name: 'zocdoc', definition: zocdocTokenDefinition },
  { name: 'schweiger', definition: schweigerTokenDefinition },
  { name: 'privia', definition: priviaTokenDefinition },
  { name: 'womensCare', definition: womensCareTokenDefinition },
];

for (const { name, definition } of themes) {
  const theme = generateThemeSync(definition, { dryRun: true });

  const output = `// Generated by scripts/generate-themes.ts — do not edit
export const ${name}ThemeCss = ${JSON.stringify(theme.css ?? '')};
export const ${name}ResetCss = ${JSON.stringify(theme.cssReset ?? '')};
export const ${name}UtilitiesCss = ${JSON.stringify(theme.cssUtilities ?? '')};
export const ${name}AllCss = [${name}ThemeCss, ${name}ResetCss, ${name}UtilitiesCss].join('\\n');
`;

  writeFileSync(resolve(outDir, `${name}.ts`), output);
  console.log(`Generated ${name}.ts`);
}

console.log('Theme CSS generation complete.');
